"""initial schema

Revision ID: 421167862978
Revises: 
Create Date: 2026-04-30 19:52:40.696273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421167862978'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_remote_configs_client_uuid', table_name='remote_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_remote_configs_client_uuid', 'remote_configs', ['client_uuid'], unique=False)
    # ### end Alembic commands ###
