"""initial commit

Revision ID: 62ab15aa1171
Revises: 
Create Date: 2026-04-30 20:34:07.044572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ab15aa1171'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('server_created', 'configs_refreshed', 'subscription_created', 'subscription_updated', 'item_created', 'item_updated', 'item_deleted', 'apply_started', 'apply_finished', 'cache_refreshed', 'cache_cleared', 'traffic_read', name='auditeventtype'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('panel_url', sa.Text(), nullable=False),
    sa.Column('panel_username', sa.String(length=128), nullable=False),
    sa.Column('panel_password', sa.Text(), nullable=False),
    sa.Column('subscription_base_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'down', name='serverstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_config_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config_refresh_error', sa.Text(), nullable=True),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_userinfo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('remote_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('inbound_remark', sa.String(length=255), nullable=True),
    sa.Column('inbound_protocol', sa.String(length=64), nullable=True),
    sa.Column('inbound_port', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=128), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_sub_id', sa.String(length=255), nullable=True),
    sa.Column('client_enable', sa.Boolean(), nullable=True),
    sa.Column('client_expiry_time', sa.Integer(), nullable=True),
    sa.Column('client_total_gb', sa.BigInteger(), nullable=True),
    sa.Column('client_up', sa.BigInteger(), nullable=True),
    sa.Column('client_down', sa.BigInteger(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'missing', name='remoteconfigstatus'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'inbound_id', 'client_uuid', name='uq_remote_config_identity')
    )
    op.create_index(op.f('ix_remote_configs_client_email'), 'remote_configs', ['client_email'], unique=False)
    op.create_index(op.f('ix_remote_configs_client_sub_id'), 'remote_configs', ['client_sub_id'], unique=False)
    op.create_index(op.f('ix_remote_configs_server_id'), 'remote_configs', ['server_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('shared_sub_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'expired', name='subscriptionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traffic_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_shared_sub_id'), 'subscriptions', ['shared_sub_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_token'), 'subscriptions', ['token'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('subscription_hwids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'hwid', name='uq_subscription_hwid')
    )
    op.create_index(op.f('ix_subscription_hwids_hwid'), 'subscription_hwids', ['hwid'], unique=False)
    op.create_index(op.f('ix_subscription_hwids_subscription_id'), 'subscription_hwids', ['subscription_id'], unique=False)
    op.create_table('subscription_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_uuid', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'synced', 'error', 'disabled', name='itemstatus'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_items_server_id'), 'subscription_items', ['server_id'], unique=False)
    op.create_index(op.f('ix_subscription_items_subscription_id'), 'subscription_items', ['subscription_id'], unique=False)
    op.create_table('subscription_source_caches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('normalized_links', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'server_id', name='uq_subscription_source_cache')
    )
    op.create_index(op.f('ix_subscription_source_caches_server_id'), 'subscription_source_caches', ['server_id'], unique=False)
    op.create_index(op.f('ix_subscription_source_caches_subscription_id'), 'subscription_source_caches', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_source_caches_subscription_id'), table_name='subscription_source_caches')
    op.drop_index(op.f('ix_subscription_source_caches_server_id'), table_name='subscription_source_caches')
    op.drop_table('subscription_source_caches')
    op.drop_index(op.f('ix_subscription_items_subscription_id'), table_name='subscription_items')
    op.drop_index(op.f('ix_subscription_items_server_id'), table_name='subscription_items')
    op.drop_table('subscription_items')
    op.drop_index(op.f('ix_subscription_hwids_subscription_id'), table_name='subscription_hwids')
    op.drop_index(op.f('ix_subscription_hwids_hwid'), table_name='subscription_hwids')
    op.drop_table('subscription_hwids')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_token'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_shared_sub_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_remote_configs_server_id'), table_name='remote_configs')
    op.drop_index(op.f('ix_remote_configs_client_sub_id'), table_name='remote_configs')
    op.drop_index(op.f('ix_remote_configs_client_email'), table_name='remote_configs')
    op.drop_table('remote_configs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('servers')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
