"""daily traffic snapshots and maintenance

Revision ID: cea2e27652ee
Revises: 62ab15aa1171
Create Date: 2026-05-13 19:54:01.160585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea2e27652ee'
down_revision: Union[str, None] = '62ab15aa1171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_traffic_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_telegram_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_title', sa.String(length=128), nullable=True),
    sa.Column('subscription_token', sa.String(length=128), nullable=True),
    sa.Column('subscription_item_id', sa.String(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('server_name', sa.String(length=128), nullable=True),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('inbound_remark', sa.String(length=255), nullable=True),
    sa.Column('inbound_protocol', sa.String(length=64), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_uuid', sa.String(length=128), nullable=True),
    sa.Column('remote_config_id', sa.String(), nullable=True),
    sa.Column('remote_config_status', sa.String(length=32), nullable=True),
    sa.Column('up', sa.BigInteger(), nullable=False),
    sa.Column('down', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('traffic_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'snapshot_type', 'traffic_key', name='uq_daily_traffic_snapshot_identity')
    )
    op.create_index(op.f('ix_daily_traffic_snapshots_client_email'), 'daily_traffic_snapshots', ['client_email'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_client_uuid'), 'daily_traffic_snapshots', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_remote_config_id'), 'daily_traffic_snapshots', ['remote_config_id'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_server_id'), 'daily_traffic_snapshots', ['server_id'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_snapshot_at'), 'daily_traffic_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_snapshot_date'), 'daily_traffic_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_snapshot_type'), 'daily_traffic_snapshots', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_subscription_id'), 'daily_traffic_snapshots', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_subscription_item_id'), 'daily_traffic_snapshots', ['subscription_item_id'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_traffic_key'), 'daily_traffic_snapshots', ['traffic_key'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_user_id'), 'daily_traffic_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_traffic_snapshots_user_telegram_id'), 'daily_traffic_snapshots', ['user_telegram_id'], unique=False)
    op.create_table('maintenance_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_step', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_type', 'run_date', name='uq_maintenance_run_type_date')
    )
    op.create_index(op.f('ix_maintenance_runs_run_date'), 'maintenance_runs', ['run_date'], unique=False)
    op.create_index(op.f('ix_maintenance_runs_run_type'), 'maintenance_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_maintenance_runs_status'), 'maintenance_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_runs_status'), table_name='maintenance_runs')
    op.drop_index(op.f('ix_maintenance_runs_run_type'), table_name='maintenance_runs')
    op.drop_index(op.f('ix_maintenance_runs_run_date'), table_name='maintenance_runs')
    op.drop_table('maintenance_runs')
    op.drop_index(op.f('ix_daily_traffic_snapshots_user_telegram_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_user_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_traffic_key'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_subscription_item_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_subscription_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_snapshot_type'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_snapshot_date'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_snapshot_at'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_server_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_remote_config_id'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_client_uuid'), table_name='daily_traffic_snapshots')
    op.drop_index(op.f('ix_daily_traffic_snapshots_client_email'), table_name='daily_traffic_snapshots')
    op.drop_table('daily_traffic_snapshots')
    # ### end Alembic commands ###
