"""add subscription last requested at

Revision ID: e2ba3e0bf456
Revises: 04e22974b2db
Create Date: 2026-05-14 13:46:39.738664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ba3e0bf456'
down_revision: Union[str, None] = '04e22974b2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_requested_at')
    # ### end Alembic commands ###
